swagger: "2.0"
info:
  version: 0.0.0
  title: title
  description: description
  termsOfService: terms
  contact:
    name: 
    url: 
    email: 
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

title: Swagger Sample App
description: This is a sample server Petstore server.
termsOfService: http://swagger.io/terms/
contact:
  name: API Support
  url: http://www.swagger.io/support
  email: support@swagger.io
license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.1
paths:
  